#!/usr/bin/env sh

# kak_open [+line] <file>: open <file> in the calling Kakoune client
if [ $# = 2 ]; then
    line=${1#+}
    [ "$line" = 0 ] && line=1
    file=$2
else
    line=''
    file=$1
fi
# quote for kakoune: double every " in the file name
file=$(printf %s "$file" | sed 's/"/""/g')
echo "evaluate-commands -client $KAK_CLIENT -verbatim -- edit \"$file\" $line" | kak -p "$KAK_SESSION"
