#!/usr/bin/env sh

# one parameter, which corresponds to the file name
[ $# = 1 ] && echo "evaluate-commands -client $KAK_CLIENT edit $1" | kak -p "$KAK_SESSION"
# two parameters, which correspond to the +line number and the file name
if [ $# = 2 ]
then
    [ "$1" = '+0' ] && LINE=1 || LINE=$1
    echo "evaluate-commands -client $KAK_CLIENT edit $2" | kak -p "$KAK_SESSION" && \
    echo "execute-keys -client $KAK_CLIENT ${LINE}g" | kak -p "$KAK_SESSION"
fi
